# Conexão com o banco H2
spring.r2dbc.url=r2dbc:h2:mem:///cache;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.r2dbc.username=sa
spring.r2dbc.password=

# H2 console habilitado
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.sql.init.mode=always

# Log
logging.level.root=INFO
logging.level.org.springframework.cache=TRACE
logging.level.com.napoleao.async.cache=INFO
# Config opcional: logar queries SQL
logging.level.org.springframework.r2dbc.core=DEBUG

# cache
spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# application
application.cacheTTL=30